#!/usr/bin/python2
import os, time
def debbased():
    print('\033[92mLOADED DEBIAN\033[0m')
    print('first time to setup sudo (run as root)')
    name = raw_input('give the name of the user you want to add to the sudo group: ')
    os.system('adduser %s sudo' %name)
    print('time to (probably) quick update')
    print('ignore apt warnings')
    time.sleep(4)
    os.system('sudo apt update > /dev/null && sudo apt upgrade -y > /dev/null')
    print('\033[93mok updates done now time to install some important packages\033[0m')
    os.system('sudo apt install -y clamav needrestart debsums synaptic apt-listbugs gksu debsecan ufw clamav auditd sysstat > /dev/null')
    print('done\nnow AUTOmate will setup firewall')
    os.system('sudo ufw default deny incoming && sudo ufw default allow outgoing && ufw enable')
    nig = raw_input("ok some info u want to say to users which got ur computer")
    os.system('sudo echo "%s" > /etc/issue' %nig)
    os.system('sudo echo "%s" > /etc/issue.net' %nig)
    os.system('sudo apt autoremove && apt autocean')
    print('ok so now time for virus scan (yep on linux it is good to do it)')
    print('scanning...')
    os.system('clamav --bell --recursive -i --follow-dir-symlinks=2 --detect-pua=yes --algorithmic-detection=yes /')
    print('done')
debbased()
