#!/usr/bin/python2
import os, time
def debian():
    print('\033[93mRUN AS ROOT\033[0m')
    print('first time to setup sudo (run as root)')
    name = raw_input('give the name of the user you want to add to the sudo group (type nothing to continue): ')
    if name != "":
        os.system('adduser %s sudo' %name)
    print('adding now repositories with more software')
    os.system('rm /etc/apt/sources.list && echo "deb http://deb.debian.org/debian stretch main contrib non-free\ndeb-src http://deb.debian.org/debian stretch main contrib non-free\n\ndeb http://deb.debian.org/debian-security/ stretch/updates main contrib non-free\ndeb-src http://deb.debian.org/debian-security/ stretch/updates main contrib non-free\n\ndeb http://deb.debian.org/debian stretch-updates main contrib non-free\ndeb-src http://deb.debian.org/debian stretch-updates main contrib non-free" > /etc/apt/sources.list && dpkg --add-architecture i386')
    print('time to (probably) quick update')
    print('ignore apt warnings')
    time.sleep(4)
    os.system('sudo apt update && sudo apt upgrade -y')
    print('\033[93mok updates done now time to install some important packages\033[0m')
    os.system('sudo apt install -y wget bleachbit preload arc-theme moka-icon-theme firmware-linux clamav gdebi needrestart debsums synaptic gksu fail2ban debsecan ufw clamav auditd sysstat')
    print('done\nnow debian-purge will setup firewall')
    os.system('sudo ufw default deny incoming && sudo ufw default allow outgoing && ufw enable')
    nig = raw_input("ok some info u want to say to users who will see on your computer (nothing to continue) : ")
    if nig != "":
        os.system('echo "%s" > /etc/issue' %nig)
        os.system('echo "%s" > /etc/issue.net' %nig)
    os.system('apt autoremove && apt autocean')
    print('ok so now time for virus scan (yep on linux it is good to do it)')
    print('but before need to update virus definitions db\nwait...')
    os.system('sudo freshclam')
    print('scanning...')
    os.system('clamscan --bell --recursive -i --follow-dir-symlinks=2 --detect-pua=yes --algorithmic-detection=yes /')
    print('done')
    print('now some better icons than default...')
    os.system("sudo apt install -y apt-lisbugs")
    os.system('wget https://launchpadlibrarian.net/383884507/paper-icon-theme_1.5.721-201808151353~daily~ubuntu18.04.1_all.deb > /dev/null')
    os.system('dpkg -i paper* && sudo apt install -f && rm paper*')
    print('change icons in apperance menu or in tweaks')
    os.system('reset && history -c')
    print('done enjoy :)')
debian()
